import mongoose from "mongoose";

const StudentSchema = new mongoose.Schema({
  studentName: { type: String, required: true },
  registrationNo: { type: Number, required: true },
  class: { type: String, required: true },
  admissionDate: { type: String, required: true },
  discountPercentage: { type: Number, required: true },
  mobileNo: { type: String },
  cnic: { type: Number, required: true },
  dateOfBirth: { type: String, required: true },
  orphan: { type: Boolean },
  gender: { type: String, required: true },
  cast: { type: String },
  osc: { type: Boolean },
  identityMark: { type: String },
  previousSchool: { type: String },
  religion: { type: String, required: true },
  bloodGroup: { type: String },
  totalSiblings: { type: Number, required: true },
  previousId: { type: String },
  fatherName: { type: String, required: true },
  fatherNationalId: { type: Number, required: true },
  occupation: { type: String },
  education: { type: String, required: true },
  fatherMobileNo: { type: String, required: true },
  profession: { type: String },
  income: { type: Number },
  motherName: { type: String, required: true },
  motherNationalId: { type: String },
  motherOccupation: { type: String },
  motherEducation: { type: String },
  motherMobileNo: { type: String },
  motherProfession: { type: String },
  motherIncome: { type: Number },
  address: { type: String, required: true },
});

export const Student = mongoose.model("Student", StudentSchema);
